version: "3.8"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
    depends_on:
      - mongodb
    networks:
      - cine-network
    command: ["npm", "run", "test"]  # Ejecutar las pruebas automáticamente
  mongodb:
    image: mongo:7.0.14
    volumes:
      - mongo-test-data:/data/db
    networks:
      - cine-network
volumes:
  mongo-test-data:
networks:
  cine-network:
