version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
